version: "2.1"
services:
  test:
    build:
      context: ../../../
      dockerfile: docker/dev/Dockerfile
    volumes_from:
      - cache
    depends_on:
      db:
        condition: service_healthy 
    environment:
      DJANGO_SETTINGS_MODULE: todobackend.settings.test
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password 
      TEST_OUTPUT_DIR: /reports

  cache:
    build: 
      context: ../../../
      dockerfile: docker/dev/Dockerfile
    volumes:
     - /tmp/cache:/cache
    entrypoint: "true"

  db:
    image: mysql:5.6
    hostname: db
    expose: 
      - "3306"    
    environment:
      MYSQL_ROOT_PASSWORD: password 
    healthcheck:
      test: mysqladmin -uroot -ppassword ping
      interval: 2s
      timeout: 5s
      retries: 30
      
